export { default as ArrowLeftIcon } from './icons/ArrowLeft';
export { default as ArrowRightIcon } from './icons/ArrowRight';
export { default as BarrierIcon } from './icons/Barrier';
export { default as BarrierStrictIcon } from './icons/BarrierStrict';
export { default as BellIcon } from './icons/Bell';
export { default as BellFillIcon } from './icons/BellFill';
export { default as BubbleIcon } from './icons/Bubble';
export { default as BubbleFillIcon } from './icons/BubbleFill';
export { default as CameraIcon } from './icons/Camera';
export { default as CameraFillIcon } from './icons/CameraFill';
export { default as CrossIcon } from './icons/Cross';
// export { default as Icon } from './icons/';
// export { default as Icon } from './icons/';
// export { default as Icon } from './icons/';
// export { default as Icon } from './icons/';
// export { default as Icon } from './icons/';
// export { default as Icon } from './icons/';
export { default as StarIcon } from './icons/Star';
export { default as StarFillIcon } from './icons/StarFill';
