export { default as ArrowLeftIcon } from './icons/ArrowLeft';
export { default as ArrowRightIcon } from './icons/ArrowRight';
export { default as BarrierIcon } from './icons/Barrier';
export { default as BarrierStrictIcon } from './icons/BarrierStrict';
export { default as BellIcon } from './icons/Bell';
export { default as BellFillIcon } from './icons/BellFill';
export { default as BubbleIcon } from './icons/Bubble';
export { default as BubbleFillIcon } from './icons/BubbleFill';
export { default as CameraIcon } from './icons/Camera';
export { default as CameraFillIcon } from './icons/CameraFill';
export { default as CrossIcon } from './icons/Cross';
// export { default as Icon } from './icons/';
// export { default as Icon } from './icons/';
// export { default as Icon } from './icons/';
// export { default as Icon } from './icons/';
// export { default as Icon } from './icons/';
// export { default as Icon } from './icons/';
export { default as StarIcon } from './icons/Star';
export { default as StarFillIcon } from './icons/StarFill';
export { default as ErrorFillIcon } from './icons/ErrorFill';
export { default as HeartIcon } from './icons/Heart';
export { default as HeartFillIcon } from './icons/HeartFill';
export { default as HomeIcon } from './icons/Home';
export { default as HomeFillIcon } from './icons/HomeFill';
export { default as MailIcon } from './icons/Mail';
export { default as MoreIcon } from './icons/More';
export { default as PaperPlaneIcon } from './icons/PaperPlane';
export { default as PersonIcon } from './icons/Person';
export { default as PersonFillIcon } from './icons/PersonFill';
export { default as PersonMinusIcon } from './icons/PersonMinus';
export { default as PersonWarningIcon } from './icons/PersonWarning';
export { default as PlusIcon } from './icons/Plus';
export { default as SearchIcon } from './icons/Search';
export { default as ShareIcon } from './icons/Share';
export { default as SuccessFillIcon } from './icons/SuccessFill';
export { default as WarningIcon } from './icons/Warning';
export { default as WarningFillIcon } from './icons/WarningFill';
